Yamakaky/rust-bindgen

- src/gen.rs
- tests/support.rs
- tests/test_builtins.rs
- tests/test_func.rs
- tests/test_struct.rs
- tests/test_union.rs
gen.rs
- Structs and unions now emit an implementation of the `Default` trait
using `std::mem::zeroed` to create a zeroed instance.
tests/support.rs
- AST comparisons are now done on the pretty-printed version of the
ASTs.  Differences in AttrIds and some identifiers (generated with
gensym to ensure uniqueness) made it unreliable to compare the ASTs
directly.  This way should work, even if it doesn't score many points
for style.
tests/*
- Updated to use `Default::default()` where appropriate.
- Eliminated a few warnings.
> Adds Default impls for generated composites.

- src/gen.rs
Currently, in generated code, fixed-sized array types are outputted using the 'u' integer suffix instead of the 'us' suffix. ie. `[::libc::c_uchar; 12u]` instead of `[::libc::c_uchar; 12us]`. This causes generated code to generate loads of warnings.
Fixing this is as simple as telling the pretty printer that we're using the non-deprecated integer types instead of the deprecated ones.
> Use usize/us instead of uint/u in generated code

- src/bin/bindgen.rs
Before:
$ bindgen nosuchfile.h && echo ok
ERROR:bindgen: No input files given
ok
After:
$ bindgen nosuchfile.h && echo ok
ERROR:bindgen: No input files given
> set return code on non-panic errors

- src/clang.rs
I was unable to compile rust-bindgen with the newest nightly.
Problem seems to have been the unboxed closure syntax, so
I quickly updated it.
> Update unboxed closure syntax.

- build.rs
- src/bgmacro.rs
- src/lib.rs
- src/parser.rs
On Fedora machines (and I believe CentOS and RHEL too), `libclang.so` is stored either on `/usr/lib/llvm` on `/usr/lib64/llvm`, depending on whether the system is 64 bits or not.
This PR changes the build script to also search for `libclang.so` on these directories, making it possible to build `rust-bindgen` on fedora without setting any environment variables.
This PR is based on top of #174, because I couldn't build on the current Rust otherwise. Let me know if I should rebase back to bindgen master.
> Allow build script to search libclang.so on multiple directories on Linux

- src/clang.rs
- src/gen.rs
ExpansionConfig now takes a Features arg instead of enable_quotes.
> upstream rust changes

- src/bgmacro.rs
- src/clang.rs
- src/gen.rs
Passes `cargo build`, and I can use it to generate `termios.rs` bindings (forcing static linking the libclang)
> fix: update to rust nightly

- Cargo.toml
- build.rs
- src/bgmacro.rs
- src/clang.rs
- src/gen.rs
I use rust-bindgen as a build-dependency, but it only works if it was statically linked to libclang. IMO a cargo feature makes it easier to select between static and dynamic linking.
This is rebased on top of #181
> add a cargo feature to statically link to libclang

- src/gen.rs
The `Copy` trait requires that the implementor is also `Clone`. Currently,
generated types have a `#[derive(Copy)]` but are missing the `Clone`
implementation.
With this patch, bindgen now adds a `Clone` implementation to each generated
struct/enum. Clone is implemented as a copy because the generated types already
have a `#[derive(Copy)]`
Sample output:
```
#[repr(C)]
#[derive(Copy)]
pub struct Struct_termios {
pub c_iflag: tcflag_t,
pub c_oflag: tcflag_t,
pub c_cflag: tcflag_t,
pub c_lflag: tcflag_t,
pub c_line: cc_t,
pub c_cc: [cc_t; 32usize],
pub c_ispeed: speed_t,
pub c_ospeed: speed_t,
}
impl ::std::clone::Clone for Struct_termios {
fn clone(&self) -> Struct_termios { *self }
}
impl ::std::default::Default for Struct_termios {
fn default() -> Struct_termios { unsafe { …
```
> fix: `impl Clone` on generated structs/enums

- plugin/Cargo.toml
- plugin/src/bgmacro.rs
- plugin/src/lib.rs
- src/lib.rs
This is a workaround while #89 is still breaking bindgen for many people.
I haven't tested if the plugin still works, as it always crashed for me
because of that bug.
> Move rustc plugin out into its own crate.

- src/gen.rs
This was tested on rustc 1.0.0-dev (f46c4e158 2015-04-20) (built 2015-04-20).
The commit in rust that appears to have introduced the problem is
https://github.com/rust-lang/rust/commit/d14109ec7e90f42a7cb966415b96094b146d3706
This change will likely break with older versions of rust (e.g. 1.0 beta),
so it may be worth sitting on its inclusion into master for some
time.
> rustup: add required trace_mac when declaring ExpansionCfg

- build.rs
ref #202.
In Ubuntu and Debian based Linux, `libclang.so` is placed in `/usr/lib/x86_64-linux-gnu`.
These Linux distributions does not put `libclang.so` to `/usr/lib`, `/usr/lib/llvm` and `/usr/lib64/llvm`.
```bash
% locate libclang.so
/usr/lib/llvm-3.4/lib/libclang.so
/usr/lib/llvm-3.4/lib/libclang.so.1
/usr/lib/x86_64-linux-gnu/libclang.so
/usr/lib/x86_64-linux-gnu/libclang.so.1
```
After this change, `cargo build` succeeded without specifying environment variables in Ubuntu 14.04.2 LTS.
```log
% cargo build
Compiling bindgen v0.14.0 (file:///home/cosmo/Github/rust-bindgen)
Compiling bitflags v0.1.1
Compiling libc v0.1.6
Compiling unicode-xid v0.0.1
Compiling term v0.2.7
Compiling rustc-serialize v0.3.14
Compiling syntex_fmt_macros v0.4.2
Compiling log v0.3.1
Compiling syntex_syntax …
```
> Add architecture triples for Ubuntu and Debian based Linux

- bindgen_plugin/src/bgmacro.rs
- src/bin/bindgen.rs
- src/lib.rs
We do the same thing for the `bindgen` binary (see #196).
---
I was hitting #85 when using the `bindgen!` plugin, applying the workaround #196 to the `bindgen!` plugin fixed the  issue.
> add `-I /path/to/clang/include` to clang args used in the `bindgen!` plugin

- src/clang.rs
- src/gen.rs
- src/parser.rs
- src/types.rs
This patch adds a few things to enable this:
* Cursor::extent
* struct Token
* TranslationUnit::tokens
- clang's C API doesn't have a straightforward way to get the integer
literal from a variable declaration, so I used clang_tokenize to
get the literal token and parse it.
* VarInfo::val - to store the value.
Non-const variable declarations and non-integer constants are handled as
they were previously.
> Add support for generating consts for integer constants. Fixes #145.

- bindgen_plugin/src/bgmacro.rs
.eat() will eat a token at *any* position in the input, and there's always an EOF,
so the loop that was meant to loop over all the arguments was instead always terminating
after the first one.
parser.check(&token::Eof) returns true iff the *next* token is EOF, which is what we want.
> Use parser.check(&token::Eof) rather than .eat().

- src/clang.rs
- src/gen.rs
- src/parser.rs
- src/types.rs
- tests/headers/struct_with_packing.h
- tests/test_struct.rs
I have lately been toying with the Linux DVB API, and have used rust-bindgen to ease the use of the C API headers. It took me a while to realize I couldn't pass an array of structs properly when making a ioctl call, because the struct has __attribute__((packed)) as defined in the Linux headers while the Rust equivalent lacked repr(packed). Adding it fixed the problem, but of course it would be nice to not have to touch bindgen-generated source.
Clang luckily already supports the (originally GCC specific, if not counting clang) attribute. Getting the corresponding Rust struct definitions to have repr(C, packed) wasn't terribly difficult, so here I present this PR. However, I wouldn't say I'm very well versed in C nor (lib)clang - or rust-bindgen itself - so it is still very much possible I …
> Add support for packed attribute

- build.rs
On Debian/Ubuntu-like systems, `libclang.so` is provided by `libclang-dev` (or versioned alternatives, like `libclang-3.4-dev`), and is found only in versioned directories. This is a relatively cheesy fix, but simple and convenient.
Fixes crabtw/rust-bindgen#202 without the ick, fixes crabtw/rust-bindgen#203, and probably fixes crabtw/rust-bindgen#189.
> Add Debian/Ubuntu locations to clang search paths

- src/bin/bindgen.rs
- src/lib.rs
This ensures that Clang always can find its bundled libraries. Without the patch it's not true for library invocations, only for the bundled utility. One example is that on NixOS, where headers are located in non-standard directory, tests will fail.
This also uses second include path, allowing one to override it if wanted.
> Add bundled Clang includes in default options

- src/gen.rs
- tests/headers/enum.h
- tests/headers/enum_dupe.h
- tests/headers/enum_explicit_type.hpp
- tests/headers/enum_negative.h
- tests/headers/enum_packed.h
- tests/support.rs
- tests/test_enum.rs
- tests/tests.rs
Duplicate values end up as constants of the same enum type. Most enums
are repr(u32) as they should, except for those with attribute((packed)),
which are of the smallest representation possible.
> Translate C enums to Rust enums

- src/parser.rs
- tests/headers/extern.hpp
- tests/support.rs
- tests/test_extern.rs
- tests/tests.rs
This fixes functions that use extern "C".
> Recurse into unexposed decls

- src/gen.rs
- tests/test_decl.rs
- tests/test_extern.rs
- tests/test_func.rs
- tests/test_struct.rs
- tests/test_union.rs
two things that occurred to me while working on this:
- Should this change land behind a BindgenOption? That way, by default, bindgen uses the libc types, and when the option is enabled bindgen uses std::os::raw types.
- This patch use the std::os::raw types, but it's also possible to use the core::os::raw types. We could add, later, a `nostd` option to BindgenOptions that let the user pick between the core or the std types.
cc @mbrubeck
> use std::os::raw types instead of libc's

- src/lib.rs
Similar to #242. In my system, clang is a symlink to a versioned clang (e.g.
clang-3.7), and this equality check to "clang" was failing.
This patch makes the check more robust so it can match "clang" or "clang-3.7",
but still reject a symlink to ccache.
> make get_clang_dir more robust

- src/clang.rs
- src/clangll.rs
- tests/tests.rs
Reduce the number of `libc` types.
Now only `time_t` in `libc` is used. All others are using `std::os::raw` now.
> Use std instead of libc whenever possible

- Cargo.toml
This should result in a more informative listing on crates.io.
> Add meta-data to Cargo.toml and remove extra newlines.

- Cargo.toml
- src/gen.rs
- src/lib.rs
- src/types.rs
The changes I have made appease those lints enabled by default in `clippy 0.0.50`.
I have disabled the `if_not_else` and `items_after_statements` lints because appeasing them would lead to a lot of code movement without meaningful gains.
`needless_lifetimes` seems to have a false positive on `Bindings::write()`.
> Add clippy

- Changelog.md
- src/gen.rs
- src/parser.rs
- src/types.rs
- tests/headers/struct_with_anon_enum.h
- tests/headers/struct_with_anon_enum_bitfields.h
- tests/test_struct.rs
See issue #292 for details.
This also includes a small patch to `build.rs` to fix issue rust-lang/cargo#2478.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/297)
> Support for inline enum declarations in struct fields

- README.md
show status of master branch only
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/337)
> revert Travis CI status shield to shields.io

- src/main.rs
`File::open` opens the file [in read-only mode](https://doc.rust-lang.org/std/fs/struct.File.html#method.open) - which isn't very useful for an output file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/341)
> Open output file with write permissions

- src/main.rs
The C library that I'm binding to needs to be `link=cares` on Unix but `link=libcares` on Windows.
It's more convenient to do neither of these and instead provide `links = "cares"` in Cargo.toml, which works for both cases.
Therefore I'd like to make the "link" command line option optional.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/343)
> Make link command line option optional

- src/main.rs
Note that it seems there were plans to add the `--match=<name>...` syntax support into docopt - https://github.com/docopt/docopt/issues/38#issuecomment-7068078 - but I've tried it with http://try.docopt.org and it doesn't work. Meaning we have to add a `Usage:` line for the multiple arguments option to work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/363)
> Bring back multiple matches support. Closes #362.

- src/gen.rs
- tests/test_keywords.rs
- tests/test_prefix.rs
The proper and only way to set the link name of an item is by using `#[link_name = "NAME"]`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/366)
> Fix link_name attribute generation

- src/gen.rs
- tests/headers/cyclic.h
- tests/test_prefix.rs
Because of the remove_prefix options, it's possible that a legitimate C typedef
would result in a cyclic Rust type alias, which results in compiler error
[E0391](https://doc.rust-lang.org/stable/error-index.html#E0391).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/365)
> Ignore typedefs if they would result in a cyclic reference in Rust.

- .travis.yml
- scripts/travis-before-install.sh
Moving the before_install stuff into a standalone script makes it much more readable and easier to edit in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/374)
> [travis] Move before_install into a script

- src/gen.rs
- tests/test_enum.rs
- tests/test_prefix.rs
* Make types public
* Remove prefixes from the elements
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/371)
> Various fixes for enum types that are not converted into enums

- Cargo.toml
- Changelog.md
- src/clang.rs
- src/lib.rs
- src/main.rs
- src/parser.rs
- tests/headers/defines.h
- tests/test_defines.rs
- tests/tests.rs
This uses [cexpr](https://crates.io/crates/cexpr) to parse the definitions.
Future improvements that I'm not going to work on any time soon, but shouldn't be too hard now that the parser is written:
* cexpr also supports parsing strings, chars, and floats, but bindgen can't currently define variables of those types.
* cexpr could also be used to enhance literal parsing for variables, replacing `parser.rs:visit_literal()`.
Fixes #56
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/370)
> Add support for parsing macro definitions

- Changelog.md
- src/gen.rs
- tests/headers/func_ptr.h
- tests/test_extern.rs
- tests/test_func.rs
Pointers to function pointers now generate the correct number of indirections
Fixes #212
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/375)
> Ignore the last ptr to a FuncProto

- Changelog.md
- src/gen.rs
- tests/headers/struct_with_aligned_struct.h
- tests/test_struct.rs
Issue #353 
I think this does it. The output looks OK. For fields that have implicit padding, no padding is emitted (so { int32 a; char b } won't explicitly get the 3 bytes of padding it actually has.
I changed the order of the u64 and u8 padding as the calculation was wrong (it wouldn't take into account the alignment of the u64 array). Now it emits enough of a u8 array to get to an 8 byte boundary, then emits the u64 arrays as needed.
Also, if the total padding needed is under max array size (32) then just one padding array of u8s is used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/364)
> Address issue #353, emit u8 padding then u64

- Cargo.toml
- README.md
- scripts/travis-before-install.sh
- src/clang.rs
- src/gen.rs
- src/parser.rs
- src/types.rs
I had to make breaking changes in `clang-sys` to avoid undefined behavior (KyleMayes/clang-sys#42) that led to crashes with `libclang` 3.9. All of the enums have been changed to constants.
This pull requests deals with the fallout from those changes (and updates the README.md and fixes some clippy warnings).
However, there is still the outstanding issue of `CXType_Elaborated`, which was added to the `CXTypeKind` enum in `libclang` 3.9. Some C types are now reported as `CXType_Elaborated`, which breaks this library when using `libclang` 3.9 (the primary culprit seems to be typedefs). I tried to fix this myself but I don't understand how this library works, so I eventually gave up.
> Bump clang-sys version

- src/main.rs
Also removes the extra usage line for --match which is unnecessary.
> Allow multiple --link args again.
