src/clang.rs
src/clangll.rs
src/lib.rs
src/macro.rs
src/types.rs

fix build on master rust

---

src/clang.rs
src/clangll.rs
src/gen.rs
src/parser.rs

see https://github.com/rust-lang/rfcs/blob/master/text/0509-collections-reform-part-2.md#entry-api-v20
Right now it is not building on latest nightly. This fixes it.

Fixes after entry api modifications

---

build.rs
src/bin/bindgen.rs
src/clang.rs
src/lib.rs

Gets bindgen building with the latest Rust master.

Fixes for std::io -> std::old_io Rust changes.

---

src/bin/bindgen.rs

Use old_path

---

build.rs
src/bgmacro.rs
src/bin/bindgen.rs

Get compiling after upstream rust changes, clear a few warnings.

upstream rust changes

---

src/bin/bindgen.rs

Try to include clang's bundled include files if possible.

---

.travis.yml
Cargo.toml
src/lib.rs
tests/test_builtins.rs
tests/test_cmath.rs
tests/test_struct.rs
tests/test_union.rs
tests/tests.rs

- Bindgen tests run and pass on 1.0 beta
- Travis builds and tests on nightlies and beta
- Adds a `Builder` object for use in `build.rs` scripts
- Tightens up required dependency versions - should we specify exact versions? - none of these necessarily follow semver yet
Docs for all this coming soon

More 1.0 beta support

---

Cargo.toml
src/gen.rs
tests/support.rs

Update to syntex_syntax 0.7.*

---

build.rs

* Clang CMAKE project is creating the library with `libclang.dll`
instead of the usual name format `clang.dll`. Hence, added a windows
specific search pattern for clang library search.
* Replaced `cargo:rustc-flags` with individual statements for link search
path and the library link as follows: `cargo:rustc-link-search=native={}`
and `cargo:rustc-link-lib=dylib=clang`. For some reason, using rustc-flags
on windows is causing a compile error for bindgen.

Windows platform fixes

---

build.rs

fixes issues with different linux configurations by use 'lddconfig -p' , by example libclang stored as /usr/lib64/libclang.so.3.7
tested with openSUSE 13.2

use lddconfig to lookup libclang.so at linux

---

src/gen.rs
src/parser.rs
src/types.rs

Presume that a function taking a pointer is unsafe

---

bindgen_plugin/src/bgmacro.rs

Ran into some errors compiling `bindgen_plugin` on the latest nightly, mostly due to option types being replaced by results in a few places, fixed them up so it works.

Fix compiler errors

---

src/lib.rs

For some users - eg me! - the (first) clang in their path is not the real clang, but a softlink to ccache.
This commit tries to make sure that the clang that we find really is clang, by canonicalizing the path and then checking.
Note that `fs::canonicalize` is not yet stable, but it's in beta (ie Rust 1.5) so will be stable in a couple of weeks.  Probably you'll want to wait for that before considering accepting this pull.

Make sure that we really have found clang

---

bindgen_plugin/src/lib.rs

fix rustc::plugin -> rust_plugin

---

build.rs

@Yamakaky Are you on Linux? Can you check that it doesn't break anything for you? This lets us run `cargo run` from OS X.

Fix OS X build

---

build.rs
src/gen.rs
src/types.rs
tests/headers/enum_explicit_type.hpp
tests/headers/overflowed_enum.hpp
tests/support.rs
tests/test_enum.rs

* Makes build.rs not run again when the build is fresh.
* Makes it support long long enums.
* Fixes the bug in #232.

Some enum and build fixes

---

tests/headers/union_with_big_member.h

Fix test_union::with_derive_debug.

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/306)

Use LLVM 3.7 and 3.8 on Travis for OS X

---

src/clang.rs
src/gen.rs
src/types.rs

Please review my comments and propose your owns when they are missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/295)

Improve types.rs

---

src/gen.rs
tests/test_enum.rs
tests/test_func.rs
tests/test_struct.rs
tests/test_union.rs

Various refactoring, separated by commits.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/296)

Refactoring gen.rs

---

Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/323)

clang-sys 5.1

---

src/gen.rs
tests/headers/func_ptr_in_struct.h
tests/support.rs
tests/test_func.rs
tests/test_union.rs

Fixes #320.
One new bug \o/
The other is WIP https://github.com/crabtw/rust-bindgen/issues/319
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/321)

[tests] Try to compile the output with rustc.

---

Changelog.md
src/clang.rs
src/gen.rs
src/parser.rs
src/types.rs
tests/headers/struct_with_aligned_struct.h
tests/test_struct.rs

Resolve issue #336
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/338)

Generate padding bytes in struct base on field align and struct size

---

Cargo.toml
Changelog.md
src/lib.rs
src/main.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/340)

[main] Use docopt for arguments parsing.

---

src/main.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/354)

Expose rust_enums option in the cli

---

src/clang.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/360)

Remove unnecessary transmute

---

.travis.yml

This should hopefully fix the Travis CI builds, though it might take me more than one try.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/367)

[travis] Fix build (#357)

---

Cargo.toml
tests/support.rs
tests/tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/372)

Fix tests failing randomly

---

Changelog.md
src/gen.rs
src/parser.rs
src/types.rs
tests/headers/unsigned.h
tests/test_primitives.rs

Closes #373.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crabtw/rust-bindgen/376)

Add support to wchar_t.

---

README.md

* Updated due to ownership change
* Fixes #378

Updated documentation url in README

---

README.md

Adding an example of wrapping the generated bindings in a module to avoid the issue with `include!` and top-level inner attributes that a few people seem to be running into. Hopefully this will help people who are running into or would have run into the issue to avoid it.
Let me know if this look clear or the example is too long or such.

Update readme w/ example of wrapping the bindings
